version: 2
jobs:
  build:
    working_directory: ~/neo4j-graphiql-plugin

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout
      - restore_cache:
          key: dep1-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline # gets the project dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: dep1-{{ checksum "pom.xml" }}

      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts: 
          path: target/*.jar